# Generated by Django 4.1.1 on 2022-10-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donation_pick_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
