# Generated by Django 4.1.1 on 2022-10-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_institution_collected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='collected',
        ),
        migrations.AddField(
            model_name='donation',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
