# Generated by Django 4.1.1 on 2022-10-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_remove_institution_collected_donation_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='collect_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
