# Generated by Django 4.1.1 on 2022-10-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_donation_collect_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='collect_date',
            new_name='is_taken',
        ),
    ]
